### ISSUE TITLE
Missing character HTML breaking Plugins page table

### ISSUE THREAD

**Issue by dani-ooo** [williambargent/YOURLS-Forward-Slash-In-Urls#1]
[plugin.php](https://github.com/williambargent/YOURLS-Forward-Slash-In-Urls/blob/master/plugin.php) line 8 is missing a `"` to close the `href` attribute, and it's causing the table in the Plugins page to break.

`Author: <a href="http://williambargent.co.uk>William Bargent</a>`
=>
`Author: <a href="http://williambargent.co.uk">William Bargent</a>`

**Comment by williambargentball** [comment]
98712d61cc45e8afb9189546cdef069879e04104
